name: Tests (7.x)
on:
  repository_dispatch:
    types:
      - trigger-7x-tests

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.2', '7.3', '7.4']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: php-${{ matrix.version }}
          submodules: true
      - name: Install Dependencies
        run: composer install
      - name: Run tests
        run: composer phpunit
